# Generated by Django 4.2.3 on 2023-10-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "permissions": [
                    ("can_change_desc_permission", "Can manage blog publications")
                ],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
