# Generated by Django 4.2.3 on 2023-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    (
                        "can_change_is_published_permission",
                        "Can cancel product publication",
                    ),
                    ("can_change_desc_permission", "Can change product description"),
                    ("can_change_category_permission", "Can change product category"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
